version: "3"

services:
  apizilla:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"

  nginx:
    restart: unless-stopped
    image: nginx:1.19.2-alpine
    hostname: nginx
    container_name: nginx-container
    ports:
      - "8043:80"
      # - "443:443"
    # environment:
    #   - CERTBOT_EMAIL=youremail@gmail.com
    volumes:
      - ./nginx/http.nginx.conf:/etc/nginx/nginx.conf
      #  - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - apizilla
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"